import { WebClient } from '@slack/web-api';
import fs from 'fs';
import path from 'path';

export interface FileUploadResult {
    success: boolean;
    fileUrl?: string;
    fileId?: string;
    error?: string;
}

export class SlackFileUploadService {
    /**
     * Upload a file to Slack using files.upload_v2 API
     * @param apiToken - Slack API token (user-specific or bot token)
     */
    async uploadFile(
        channel: string,
        filePath: string,
        apiToken: string | undefined,
        title?: string,
        initialComment?: string,
        threadTs?: string
    ): Promise<FileUploadResult> {
        if (!apiToken) {
            return {
                success: false,
                error: 'API token is required'
            };
        }
        try {
            // Check if file exists
            if (!fs.existsSync(filePath)) {
                return {
                    success: false,
                    error: `File not found: ${filePath}`
                };
            }

            // Create WebClient with the provided token
            const client = new WebClient(apiToken);

            // Read file content
            const fileContent = fs.readFileSync(filePath);
            const fileName = path.basename(filePath);

            // Upload file to Slack
            const uploadParams: any = {
                channel_id: channel,
                file: fileContent,
                filename: fileName,
                title: title || fileName,
                initial_comment: initialComment || '📊 Data visualization generated by Kira'
            };

            // Add thread_ts if provided
            if (threadTs) {
                uploadParams.thread_ts = threadTs;
            }

            const result = await client.files.uploadV2(uploadParams) as any;

            // Log the result for debugging
            console.log(`📤 Upload result for ${fileName}:`, {
                ok: result.ok,
                hasFiles: !!(result.files && result.files.length > 0),
                error: result.error
            });

            // If result.ok is true, the upload succeeded (file is visible in Slack)
            // When uploading with channel_id, the response structure is: result.files[0].files[0]
            if (result.ok) {
                // Extract file information from the nested structure
                let file: any = null;
                if (result.files && result.files.length > 0) {
                    const firstFileGroup = result.files[0] as any;
                    if (firstFileGroup.files && firstFileGroup.files.length > 0) {
                        file = firstFileGroup.files[0];
                    } else if (firstFileGroup.id) {
                        // Sometimes the file is directly in the first element
                        file = firstFileGroup;
                    }
                }
                
                if (file) {
                    const fileId = file.id;
                    const fileUrl = file.url_private || file.permalink || '';
                    console.log(`✅ File uploaded successfully: ${fileUrl || 'File appears as attachment'}`);
                    return {
                        success: true,
                        fileUrl: fileUrl,
                        fileId: fileId
                    };
                } else {
                    // Upload succeeded but file info not in expected structure
                    // This is okay - when uploading with channel_id, the file appears automatically
                    console.log(`✅ File uploaded successfully (appears as attachment in channel)`);
                    return {
                        success: true,
                        fileUrl: '',
                        fileId: undefined
                    };
                }
            } else {
                // Log the full response for debugging
                console.error('❌ Slack upload failed:', JSON.stringify(result, null, 2));
                return {
                    success: false,
                    error: result.error || 'Unknown error uploading file'
                };
            }

        } catch (error: any) {
            console.error('Error uploading file to Slack:', error);
            return {
                success: false,
                error: error.message || 'Failed to upload file to Slack'
            };
        }
    }

    /**
     * Upload a file to Slack without channel_id for permanent storage
     * Returns the file URL that can be used in image blocks
     */
    async uploadFileForImage(
        filePath: string,
        apiToken: string | undefined,
        title?: string
    ): Promise<FileUploadResult> {
        if (!apiToken) {
            return {
                success: false,
                error: 'API token is required'
            };
        }
        try {
            // Check if file exists
            if (!fs.existsSync(filePath)) {
                return {
                    success: false,
                    error: `File not found: ${filePath}`
                };
            }

            // Create WebClient with the provided token
            const client = new WebClient(apiToken);

            // Read file content
            const fileContent = fs.readFileSync(filePath);
            const fileName = path.basename(filePath);

            // Upload file to Slack WITHOUT channel_id (stored but not displayed)
            const uploadParams: any = {
                file: fileContent,
                filename: fileName,
                title: title || fileName
            };

            const result = await client.files.uploadV2(uploadParams) as any;

            console.log(`📤 Upload result for ${fileName}:`, {
                ok: result.ok,
                hasFile: !!result.file,
                error: result.error
            });

            if (result.ok && result.file) {
                const file = result.file as any;
                const fileId = file.id;
                // Get the file's private download URL (requires authentication but works in Slack blocks)
                const fileUrl = file.url_private_download || file.url_private || '';
                console.log(`✅ File uploaded successfully: ${fileUrl}`);
                return {
                    success: true,
                    fileUrl: fileUrl,
                    fileId: fileId
                };
            } else {
                console.error('❌ Slack upload failed:', JSON.stringify(result, null, 2));
                return {
                    success: false,
                    error: result.error || 'Unknown error uploading file'
                };
            }

        } catch (error: any) {
            console.error('Error uploading file to Slack:', error);
            return {
                success: false,
                error: error.message || 'Failed to upload file to Slack'
            };
        }
    }

    /**
     * Clean up temporary file after upload
     */
    cleanupFile(filePath: string): void {
        try {
            if (fs.existsSync(filePath)) {
                fs.unlinkSync(filePath);
                console.log(`Cleaned up temporary file: ${filePath}`);
            }
        } catch (error) {
            console.error('Error cleaning up file:', error);
        }
    }
}

// Export class instance (no longer singleton, token is passed per call)
export const slackFileUploadService = new SlackFileUploadService();
